### PR TITLE
Add yarn support

### PR DESCRIPTION
**Pull request by morleyzhi**
Hi!

I added Yarn support to this library. If the user asks for a Yarn version, test it the same way as node and npm; if yarn is not installed and it's not tested, ignore it; if it's not installed and it is tested, return an error. 

I also added this quality-of-life improvements:

* Reorganized the library to check from a config, so any library can be added
* Added unit tests
* ignored node_modules

### CODE REVIEW

**Comment by morleyzhi** [comment]
@parshap Can you check this out and let me know what you think?

**Comment by parshap** [comment]
@morleyzhi: This is excellent. There's a couple of changes I'd like to make, mostly style. If you check the "Allow edits from maintainers" checkbox, then I can push the changes here and maybe you can help review.

**Comment by morleyzhi** [comment]
Looks like that box is checked right now, so push away!

**Comment by morleyzhi** [comment]
Looks good to me 👍

**Comment by parshap** [comment]
Merged and published to npm as `check-node-version@2.0.0`! Thanks again for the excellent pr. I really appreciated the thorough tests and documentation.

**Comment by morleyzhi** [comment]
Thanks, it was a pleasure!

**Pull request merged**
