### PR TITLE
Fix CLI by restoring shebang to new bin file

### LINKED ISSUE #32: Using npx to run check-node-version fails since 4.0.0
**Steps to reproduce:**
run `npx check-node-version@4.0.0 --package`
(instead of adding the explicit version you can also add `--ignore-existing` to make sure npx doesn't use a version from a cache)

**Output**:
```
npx: installed 13 in 1.831s
/home/karfau/.npm/_npx/18612/bin/check-node-version: line 1: syntax error near unexpected token `'./gatekeeper''
/home/karfau/.npm/_npx/18612/bin/check-node-version: line 1: `require('./gatekeeper');'
```

**Workaround** (for people that use `npx check-node-version --package` e.g. in a `preinstall` script):

fix the version to use in your script to 3.3.0 like this:
`npx check-node-version@3.3.0 --package`

### PR DESCRIPTION
**Pull request by paulmelnikow**
Closes #32

### CODE REVIEW

**Comment by karfau** [comment]
Maybe we could add something to the CI cahin to make sure it will continue to work?
e.g. adding ` && ./bin.js` to the `test` script, or adding a `postpackage` script that uses the new package to execute it? (I'm not sure about the simplest syntax for the latter one.)

**Comment by parshap** [comment]
Thanks for the fix! This is released to npm as 4.0.1.

Agreed about adding a test to catch this. Wanted to land this fix separately asap, but would I would gladly accept a PR for that.

**Comment by paulmelnikow** [comment]
Thanks!

Adding a test is a great idea! I looked into it momentarily though ran out of time this morning and agree the fix need not block on it.

**Comment by parshap** [comment]
cc @rasenplansche: in case you're interested in adding a test for this

**Comment by rasenplanscher** [comment]
@parshap 
Thanks, I'll definitely add a regression test for this, unless someone else is faster about it.
This has to keep working, of course. With `npx` as well as with `node`.

@karfau @paulmelnikow 
Thank you for the catch and the fix!

@karfau 
> e.g. adding ` && ./bin.js` to the `test` script

Something like that, but it needs to work cross-platform, and also test both as `node ./bin.js` and `npx ./bin.js`. All use-cases should be covered so this doesn't happen again 🤔

**Pull request merged**
